### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by gdreyband** [reales/OPL#1]
1.8 Demo
Mac OSX Catalina 10.15.7
Logic Pro 10.6

- Modulator refuses to select waveform 5 (reverts modulator to previous selection, sets carrier to 5)
- Frequency multiplier on both modulator and carrier won't select 12x or 15x (reverts to 1/2x)
- Keyscale attenuation order is strange on both (-0, -3, -1.5, -6). Suggest swapping -3 and -1.5 to sequential values for human readability. [-0, -1.5, -3, -6]

File menu
Default state string "Load" is unclear. Perhaps "Load Patch", "Load Preset" or "Load Library"?

Glad to see that this project is being maintained. I enjoyed working on the UI with Bruce Sutherland on the original JUCEOPLVSTi.

**Comment by reales** [comment]
Keyscale attenuation fixed on https://github.com/reales/OPL/commit/6934d7615fc85c92a400898acba77a7cda8fb4cd

**Comment by reales** [comment]
Modulator waveform 5 fixed on https://github.com/reales/OPL/commit/e7c820caf470704405e4f4e29146980900b81b2a

**Comment by reales** [comment]
Frequency multiplier fixed on https://github.com/reales/OPL/commit/3e720f32a866be15bddfb8c7cee5b88fdc2b1dac
